#!groovy

// Generated by IBM TransformationAdvisor
// Mon May 27 08:53:42 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}